### ISSUE TITLE
알고리즘 변경으로 작동하지 않는 것 같아요

### ISSUE THREAD

**Issue by 321098123** [brianairb/Riberty#1]
혹시 픽스 여유로울 때 픽스 한번 가능한가요?

**Comment by dktsudgg** [comment]
안돼ㅠㅠㅠ 잘 쓰고 있엇는뎅......

**Comment by dktsudgg** [comment]
@arusion 
엥 저는 기존에 구매했던 책들 잘 되는 것 같은데요, 혹시 새로운 책 구매 후에 안되시는 건가요?

**Comment by arusion** [comment]
@dktsudgg 아 .. 저는 뷰어 베타 최신버전인데 혹시 베타 아닌 2.7.2는 어디서 찾아야 하는지 알 수 있을까요? ㅠㅠ

**Comment by dktsudgg** [comment]
@arusion 
리디북스에서 올해 1월쯤부터 뷰어 클라이언트를 [개정](https://help.ridibooks.com/hc/ko/articles/360041597673--%EA%B3%B5%EC%A7%80-%EC%83%88-%EB%B2%84%EC%A0%84%EC%9D%98-PC%EB%B7%B0%EC%96%B4-Beta-%EC%95%88%EB%82%B4)했나봐요ㅠㅠ 공식적인 루트로는 찾지 못할 듯 합니다
